// Paginado
export const GET_COUNTRIES = 'GET_COUNTRIES'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_ORDER = 'SET_ORDER'
// Filtrado
export const FILTER_COUNTRIES_BY_CONTINENT = 'FILTER_COUNTRIES_BY_CONTINENT '
export const FILTER_COUNTRIES_BY_SEARCH = 'FILTER_COUNTRIES_BY_SEARCH'
export const FILTER_ACTIVITIES = 'FILTER_ACTIVITIES'
// Ordenamiento
export const FILTER_COUNTRIES_BY_NAME = 'FILTER_COUNTRIES_BY_NAME'
export const FILTER_COUNTRIES_BY_POPULATION = 'FILTER_COUNTRIES_BY_POPULATION'
