const GET_COUNTRIES = 'GET_COUNTRIES'
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
const FILTER_COUNTRIES_BY_CONTINENT = 'FILTER_COUNTRIES_BY_CONTINENT'

export { GET_COUNTRIES, SET_CURRENT_PAGE, FILTER_COUNTRIES_BY_CONTINENT }
